action: train # train or test
name: FUSION # name of the experiment needed for the logs
modality: ["EMG", "RGB"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: './models"/EMG_single' # checkpoint directory
logname: null # name of the logs
models_dir: "./models" # directory containing all the models

train:
  num_iter: 10000 # number of training iterations with total_batch size
  lr_steps: 3000 # steps before reducing learning rate
  eval_freq: 200 # evaluation frequency
  num_clips: 1 # clips adopted in training
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 10

test:
  num_clips: 1 # number of clips in testing
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 10

dataset:
  annotations_path: train_val_action_net # path for the annotations data
  shift: ??? # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  num_classes: 20
  RGB:
    data_path: ??? # path to RGB data
    tmpl: "img_{:010d}.jpg" # format of RGB filenames
    features_name: D1
  Event: # not neeeded for the project
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: MLP # model name
    normalize: False
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  EMG:
    model: ActionNetwork # model name
    normalize: False
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7