action: train # train or test
name: Test#1 # name of the experiment needed for the logs
batch_size: 1 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: "/content/aml23-ego/models" # directory containing all the models

train:
  num_iter: 5000 # number of training iterations with total_batch size
  lr_steps: 3000 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True

test:
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True

dataset:
  annotations_path: train_val # path for the annotations data
  shift: ??? # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  Event: # not neeeded for the project
    rgb4e: 6

# these are the action recognition models for each modality
model: LSTM_emg
  